/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 84:
                        {
                            @SuppressWarnings("hiding") Token token = new84(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 85:
                        {
                            @SuppressWarnings("hiding") Token token = new85(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 86:
                        {
                            @SuppressWarnings("hiding") Token token = new86(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 87:
                        {
                            @SuppressWarnings("hiding") Token token = new87(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 88:
                        {
                            @SuppressWarnings("hiding") Token token = new88(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 89:
                        {
                            @SuppressWarnings("hiding") Token token = new89(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwmodule(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwimport(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwclass(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwabstract(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwinterface(line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwenum(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwspecial(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwend(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwmeth(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwtype(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwinit(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwredef(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwis(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwdo(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwreadable(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwwritable(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwvar(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwintern(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwextern(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwprotected(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwprivate(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwintrude(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwif(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwthen(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwelse(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwwhile(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwloop(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwfor(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwin(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwand(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwor(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwnot(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwreturn(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwcontinue(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwbreak(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwabort(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwassert(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwnew(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwisa(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwonce(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwsuper(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwself(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwtrue(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwfalse(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwnull(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwas(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwnullable(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwisset(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKwlabel(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpar(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCpar(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObra(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCbra(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColumn(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQuad(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPluseq(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinuseq(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDotdotdot(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDotdot(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPercent(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNe(line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLe(line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLl(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGe(line, pos); }
    Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGg(line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStarship(line, pos); }
    Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBang(line, pos); }
    Token new80(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClassid(text, line, pos); }
    Token new81(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new82(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAttrid(text, line, pos); }
    Token new83(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new84(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloat(text, line, pos); }
    Token new85(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(text, line, pos); }
    Token new86(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new87(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStartString(text, line, pos); }
    Token new88(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMidString(text, line, pos); }
    Token new89(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndString(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {37, 37, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 57, 18}, {58, 58, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {91, 91, 24}, {93, 93, 25}, {95, 95, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 30}, {101, 101, 31}, {102, 102, 32}, {103, 104, 33}, {105, 105, 34}, {106, 107, 33}, {108, 108, 35}, {109, 109, 36}, {110, 110, 37}, {111, 111, 38}, {112, 112, 39}, {113, 113, 33}, {114, 114, 40}, {115, 115, 41}, {116, 116, 42}, {117, 117, 43}, {118, 118, 44}, {119, 119, 45}, {120, 122, 33}, {125, 125, 46}, },
            {{9, 9, 1}, {32, 32, 4}, },
            {},
            {{10, 10, 47}, },
            {{9, 32, -3}, },
            {{61, 61, 48}, },
            {{0, 9, 49}, {11, 12, 49}, {14, 33, 49}, {34, 34, 50}, {35, 91, 49}, {92, 92, 51}, {93, 122, 49}, {123, 123, 52}, {124, 255, 49}, },
            {{0, 9, 53}, {10, 10, 54}, {11, 12, 53}, {13, 13, 55}, {14, 255, 53}, },
            {},
            {{0, 9, 56}, {11, 12, 56}, {14, 38, 56}, {39, 39, 57}, {40, 255, 56}, },
            {},
            {},
            {},
            {{61, 61, 58}, },
            {},
            {{61, 61, 59}, },
            {{46, 46, 60}, {48, 57, 61}, },
            {},
            {{46, 46, 62}, {48, 57, 18}, },
            {{58, 58, 63}, },
            {{60, 60, 64}, {61, 61, 65}, },
            {{61, 61, 66}, },
            {{61, 61, 67}, {62, 62, 68}, },
            {{48, 57, 69}, {65, 90, 70}, {95, 95, 71}, {97, 122, 72}, },
            {},
            {},
            {{97, 122, 73}, },
            {{48, 57, 74}, {65, 90, 75}, {95, 95, 76}, {97, 97, 77}, {98, 98, 78}, {99, 109, 77}, {110, 110, 79}, {111, 114, 77}, {115, 115, 80}, {116, 122, 77}, },
            {{48, 95, -29}, {97, 113, 77}, {114, 114, 81}, {115, 122, 77}, },
            {{48, 95, -29}, {97, 107, 77}, {108, 108, 82}, {109, 110, 77}, {111, 111, 83}, {112, 122, 77}, },
            {{48, 95, -29}, {97, 110, 77}, {111, 111, 84}, {112, 122, 77}, },
            {{48, 107, -31}, {108, 108, 85}, {109, 109, 77}, {110, 110, 86}, {111, 119, 77}, {120, 120, 87}, {121, 122, 77}, },
            {{48, 95, -29}, {97, 97, 88}, {98, 110, 77}, {111, 111, 89}, {112, 116, 77}, {117, 117, 90}, {118, 122, 77}, },
            {{48, 95, -29}, {97, 122, 77}, },
            {{48, 95, -29}, {97, 101, 77}, {102, 102, 91}, {103, 108, 77}, {109, 109, 92}, {110, 110, 93}, {111, 114, 77}, {115, 115, 94}, {116, 122, 77}, },
            {{48, 95, -29}, {97, 97, 95}, {98, 110, 77}, {111, 111, 96}, {112, 122, 77}, },
            {{48, 110, -32}, {111, 111, 97}, {112, 122, 77}, },
            {{48, 95, -29}, {97, 100, 77}, {101, 101, 98}, {102, 110, 77}, {111, 111, 99}, {112, 116, 77}, {117, 117, 100}, {118, 122, 77}, },
            {{48, 95, -29}, {97, 109, 77}, {110, 110, 101}, {111, 113, 77}, {114, 114, 102}, {115, 122, 77}, },
            {{48, 95, -29}, {97, 97, 103}, {98, 113, 77}, {114, 114, 104}, {115, 122, 77}, },
            {{48, 100, -39}, {101, 101, 105}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 106}, {102, 111, 77}, {112, 112, 107}, {113, 116, 77}, {117, 117, 108}, {118, 122, 77}, },
            {{48, 95, -29}, {97, 103, 77}, {104, 104, 109}, {105, 113, 77}, {114, 114, 110}, {115, 120, 77}, {121, 121, 111}, {122, 122, 77}, },
            {{48, 109, -40}, {110, 110, 112}, {111, 122, 77}, },
            {{48, 95, -29}, {97, 97, 113}, {98, 122, 77}, },
            {{48, 103, -44}, {104, 104, 114}, {105, 113, 77}, {114, 114, 115}, {115, 122, 77}, },
            {{0, 9, 116}, {11, 12, 116}, {14, 33, 116}, {34, 34, 117}, {35, 91, 116}, {92, 92, 118}, {93, 122, 116}, {123, 123, 119}, {124, 255, 116}, },
            {},
            {},
            {{0, 255, -8}, },
            {},
            {{0, 9, 120}, {11, 12, 120}, {14, 255, 120}, },
            {},
            {{0, 255, -9}, },
            {},
            {{10, 10, 121}, },
            {{0, 255, -11}, },
            {},
            {},
            {},
            {{46, 46, 122}, },
            {{48, 57, 61}, },
            {{48, 57, 61}, },
            {},
            {},
            {{62, 62, 123}, },
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 57, 124}, {65, 90, 125}, {95, 95, 126}, {97, 122, 127}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 110, -32}, {111, 111, 128}, {112, 114, 77}, {115, 115, 129}, {116, 122, 77}, },
            {{48, 95, -29}, {97, 99, 77}, {100, 100, 130}, {101, 122, 77}, },
            {{48, 95, -29}, {97, 114, 77}, {115, 115, 131}, {116, 122, 77}, },
            {{48, 100, -39}, {101, 101, 132}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 97, 133}, {98, 122, 77}, },
            {{48, 109, -40}, {110, 110, 134}, {111, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 114, -82}, {115, 115, 135}, {116, 122, 77}, },
            {{48, 99, -81}, {100, 100, 136}, {101, 116, 77}, {117, 117, 137}, {118, 122, 77}, },
            {{48, 95, -29}, {97, 115, 77}, {116, 116, 138}, {117, 122, 77}, },
            {{48, 107, -31}, {108, 108, 139}, {109, 122, 77}, },
            {{48, 113, -30}, {114, 114, 140}, {115, 122, 77}, },
            {{48, 109, -40}, {110, 110, 141}, {111, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 111, 77}, {112, 112, 142}, {113, 122, 77}, },
            {{48, 95, -29}, {97, 104, 77}, {105, 105, 143}, {106, 115, 77}, {116, 116, 144}, {117, 122, 77}, },
            {{48, 95, -29}, {97, 97, 145}, {98, 114, 77}, {115, 115, 146}, {116, 122, 77}, },
            {{48, 97, -29}, {98, 98, 147}, {99, 122, 77}, },
            {{48, 110, -32}, {111, 111, 148}, {112, 122, 77}, },
            {{48, 99, -81}, {100, 100, 149}, {101, 122, 77}, },
            {{48, 95, -29}, {97, 118, 77}, {119, 119, 150}, {120, 122, 77}, },
            {{48, 115, -89}, {116, 116, 151}, {117, 122, 77}, },
            {{48, 107, -31}, {108, 108, 152}, {109, 122, 77}, },
            {{48, 95, -29}, {97, 98, 77}, {99, 99, 153}, {100, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 98, -103}, {99, 99, 154}, {100, 122, 77}, },
            {{48, 104, -95}, {105, 105, 155}, {106, 110, 77}, {111, 111, 156}, {112, 122, 77}, },
            {{48, 95, -29}, {97, 97, 157}, {98, 99, 77}, {100, 100, 158}, {101, 115, 77}, {116, 116, 159}, {117, 122, 77}, },
            {{48, 107, -31}, {108, 108, 160}, {109, 122, 77}, },
            {{48, 100, -39}, {101, 101, 161}, {102, 122, 77}, },
            {{48, 111, -94}, {112, 112, 162}, {113, 122, 77}, },
            {{48, 100, -39}, {101, 101, 163}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 116, 77}, {117, 117, 164}, {118, 122, 77}, },
            {{48, 111, -94}, {112, 112, 165}, {113, 122, 77}, },
            {{48, 104, -95}, {105, 105, 166}, {106, 122, 77}, },
            {{48, 113, -30}, {114, 114, 167}, {115, 122, 77}, },
            {{48, 104, -95}, {105, 105, 168}, {106, 122, 77}, },
            {{48, 104, -95}, {105, 105, 169}, {106, 122, 77}, },
            {{0, 255, -48}, },
            {},
            {{0, 9, 170}, {11, 12, 170}, {14, 255, 170}, },
            {},
            {{0, 255, -8}, },
            {},
            {},
            {},
            {{48, 122, -75}, },
            {{48, 122, -75}, },
            {{48, 122, -75}, },
            {{48, 122, -75}, },
            {{48, 113, -30}, {114, 114, 171}, {115, 122, 77}, },
            {{48, 115, -89}, {116, 116, 172}, {117, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 173}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 97, 174}, {98, 122, 77}, },
            {{48, 114, -82}, {115, 115, 175}, {116, 122, 77}, },
            {{48, 115, -89}, {116, 116, 176}, {117, 122, 77}, },
            {{48, 100, -39}, {101, 101, 177}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 108, 77}, {109, 109, 178}, {110, 122, 77}, },
            {{48, 100, -39}, {101, 101, 179}, {102, 122, 77}, },
            {{48, 114, -82}, {115, 115, 180}, {116, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 110, -32}, {111, 111, 181}, {112, 122, 77}, },
            {{48, 115, -89}, {116, 116, 182}, {117, 122, 77}, },
            {{48, 100, -39}, {101, 101, 183}, {102, 113, 77}, {114, 114, 184}, {115, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 185}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 186}, {102, 122, 77}, },
            {{48, 111, -94}, {112, 112, 187}, {113, 122, 77}, },
            {{48, 116, -112}, {117, 117, 188}, {118, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 189}, {109, 122, 77}, },
            {{48, 100, -39}, {101, 101, 190}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 106, 77}, {107, 107, 191}, {108, 122, 77}, },
            {{48, 95, -29}, {97, 117, 77}, {118, 118, 192}, {119, 122, 77}, },
            {{48, 115, -89}, {116, 116, 193}, {117, 122, 77}, },
            {{48, 99, -81}, {100, 100, 194}, {101, 122, 77}, },
            {{48, 100, -39}, {101, 101, 195}, {102, 122, 77}, },
            {{48, 116, -112}, {117, 117, 196}, {118, 122, 77}, },
            {{48, 101, -36}, {102, 102, 197}, {103, 122, 77}, },
            {{48, 98, -103}, {99, 99, 198}, {100, 122, 77}, },
            {{48, 100, -39}, {101, 101, 199}, {102, 122, 77}, },
            {{48, 109, -40}, {110, 110, 200}, {111, 122, 77}, },
            {{48, 100, -39}, {101, 101, 201}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 202}, {102, 122, 77}, },
            {{48, 117, -157}, {118, 118, 203}, {119, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 204}, {109, 122, 77}, },
            {{48, 115, -89}, {116, 116, 205}, {117, 122, 77}, },
            {{0, 255, -48}, },
            {{48, 115, -89}, {116, 116, 206}, {117, 122, 77}, },
            {{48, 113, -30}, {114, 114, 207}, {115, 122, 77}, },
            {{48, 113, -30}, {114, 114, 208}, {115, 122, 77}, },
            {{48, 106, -156}, {107, 107, 209}, {108, 122, 77}, },
            {{48, 114, -82}, {115, 115, 210}, {116, 122, 77}, },
            {{48, 104, -95}, {105, 105, 211}, {106, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 113, -30}, {114, 114, 212}, {115, 122, 77}, },
            {{48, 100, -39}, {101, 101, 213}, {102, 122, 77}, },
            {{48, 113, -30}, {114, 114, 214}, {115, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 113, -30}, {114, 114, 215}, {115, 122, 77}, },
            {{48, 116, -112}, {117, 117, 216}, {118, 122, 77}, },
            {{48, 115, -89}, {116, 116, 217}, {117, 122, 77}, },
            {{48, 107, -31}, {108, 108, 218}, {109, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 219}, {109, 122, 77}, },
            {{48, 95, -29}, {97, 97, 220}, {98, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 97, 221}, {98, 122, 77}, },
            {{48, 95, -29}, {97, 97, 222}, {98, 122, 77}, },
            {{48, 100, -39}, {101, 101, 223}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 97, 224}, {98, 122, 77}, },
            {{48, 101, -36}, {102, 102, 225}, {103, 122, 77}, },
            {{48, 113, -30}, {114, 114, 226}, {115, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 104, -95}, {105, 105, 227}, {106, 122, 77}, },
            {{48, 113, -30}, {114, 114, 228}, {115, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 229}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 230}, {102, 122, 77}, },
            {{48, 95, -29}, {97, 97, 231}, {98, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 97, 232}, {98, 122, 77}, },
            {{48, 115, -89}, {116, 116, 233}, {117, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 109, -40}, {110, 110, 234}, {111, 122, 77}, },
            {{48, 109, -40}, {110, 110, 235}, {111, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 115, -89}, {116, 116, 236}, {117, 122, 77}, },
            {{48, 101, -36}, {102, 102, 237}, {103, 109, 77}, {110, 110, 238}, {111, 122, 77}, },
            {{48, 99, -81}, {100, 100, 239}, {101, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 240}, {102, 122, 77}, },
            {{48, 97, -29}, {98, 98, 241}, {99, 122, 77}, },
            {{48, 95, -29}, {97, 102, 77}, {103, 103, 242}, {104, 122, 77}, },
            {{48, 115, -89}, {116, 116, 243}, {117, 122, 77}, },
            {{48, 98, -103}, {99, 99, 244}, {100, 122, 77}, },
            {{48, 97, -29}, {98, 98, 245}, {99, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 109, -40}, {110, 110, 246}, {111, 122, 77}, },
            {{48, 95, -29}, {97, 97, 247}, {98, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 113, -30}, {114, 114, 248}, {115, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 97, -29}, {98, 98, 249}, {99, 122, 77}, },
            {{48, 98, -103}, {99, 99, 250}, {100, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 116, -112}, {117, 117, 251}, {118, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 97, 252}, {98, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 253}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 254}, {109, 122, 77}, },
            {{48, 100, -39}, {101, 101, 255}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 256}, {102, 122, 77}, },
            {{48, 115, -89}, {116, 116, 257}, {117, 122, 77}, },
            {{48, 107, -31}, {108, 108, 258}, {109, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 259}, {109, 122, 77}, },
            {{48, 114, -82}, {115, 115, 260}, {116, 122, 77}, },
            {{48, 107, -31}, {108, 108, 261}, {109, 122, 77}, },
            {{48, 115, -89}, {116, 116, 262}, {117, 122, 77}, },
            {{48, 100, -39}, {101, 101, 263}, {102, 122, 77}, },
            {{48, 98, -103}, {99, 99, 264}, {100, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 265}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 266}, {102, 122, 77}, },
            {{48, 100, -39}, {101, 101, 267}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 95, -29}, {97, 97, 268}, {98, 122, 77}, },
            {{48, 100, -39}, {101, 101, 269}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -39}, {101, 101, 270}, {102, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 99, -81}, {100, 100, 271}, {101, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 107, -31}, {108, 108, 272}, {109, 122, 77}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 0, 1, 1, 0, 79, -1, -1, 69, -1, 52, 53, 67, 65, 56, 66, 64, 68, 83, 57, 72, 59, 75, 80, 54, 55, -1, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, -1, 1, 71, -1, 86, -1, 87, -1, 2, 2, -1, 85, 60, 61, 63, 84, -1, 58, 74, 73, 70, 76, 77, 80, 80, 80, 80, 82, 81, 81, 81, 81, 81, 81, 48, 81, 81, 81, 16, 81, 81, 81, 81, 81, 81, 25, 81, 31, 15, 81, 81, 81, 81, 81, 81, 81, 33, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, -1, 89, -1, 88, -1, 2, 62, 78, 82, 82, 82, 82, 81, 81, 32, 81, 81, 81, 81, 81, 10, 81, 81, 81, 30, 11, 81, 81, 81, 41, 81, 81, 81, 81, 40, 34, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 19, 81, 81, -1, 81, 81, 81, 81, 81, 81, 27, 8, 81, 81, 81, 13, 81, 81, 81, 81, 29, 81, 47, 42, 81, 81, 81, 81, 81, 81, 44, 81, 81, 26, 45, 12, 81, 81, 81, 38, 81, 81, 37, 5, 81, 81, 46, 81, 81, 81, 50, 51, 81, 81, 81, 81, 81, 81, 14, 81, 81, 43, 81, 28, 81, 81, 39, 81, 21, 4, 81, 20, 81, 3, 81, 81, 81, 81, 81, 35, 81, 81, 81, 81, 81, 81, 24, 81, 3, 23, 81, 81, 9, 81, 81, 6, 36, 81, 49, 81, 17, 81, 18, 7, 22, 8, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
