/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AArrayExpr extends PExpr
{
    private final LinkedList<PExpr> _exprs_ = new LinkedList<PExpr>();

    public AArrayExpr()
    {
        // Constructor
    }

    public AArrayExpr(
        @SuppressWarnings("hiding") List<PExpr> _exprs_)
    {
        // Constructor
        setExprs(_exprs_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExpr(
            cloneList(this._exprs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExpr(this);
    }

    public LinkedList<PExpr> getExprs()
    {
        return this._exprs_;
    }

    public void setExprs(List<PExpr> list)
    {
        this._exprs_.clear();
        this._exprs_.addAll(list);
        for(PExpr e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprs_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpr> i = this._exprs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
