/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAsNotnullExpr extends PExpr
{
    private PExpr _expr_;
    private TKwas _kwas_;
    private TKwnot _kwnot_;
    private TKwnull _kwnull_;

    public AAsNotnullExpr()
    {
        // Constructor
    }

    public AAsNotnullExpr(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TKwas _kwas_,
        @SuppressWarnings("hiding") TKwnot _kwnot_,
        @SuppressWarnings("hiding") TKwnull _kwnull_)
    {
        // Constructor
        setExpr(_expr_);

        setKwas(_kwas_);

        setKwnot(_kwnot_);

        setKwnull(_kwnull_);

    }

    @Override
    public Object clone()
    {
        return new AAsNotnullExpr(
            cloneNode(this._expr_),
            cloneNode(this._kwas_),
            cloneNode(this._kwnot_),
            cloneNode(this._kwnull_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAsNotnullExpr(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TKwas getKwas()
    {
        return this._kwas_;
    }

    public void setKwas(TKwas node)
    {
        if(this._kwas_ != null)
        {
            this._kwas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwas_ = node;
    }

    public TKwnot getKwnot()
    {
        return this._kwnot_;
    }

    public void setKwnot(TKwnot node)
    {
        if(this._kwnot_ != null)
        {
            this._kwnot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnot_ = node;
    }

    public TKwnull getKwnull()
    {
        return this._kwnull_;
    }

    public void setKwnull(TKwnull node)
    {
        if(this._kwnull_ != null)
        {
            this._kwnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnull_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._kwas_)
            + toString(this._kwnot_)
            + toString(this._kwnull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._kwas_ == child)
        {
            this._kwas_ = null;
            return;
        }

        if(this._kwnot_ == child)
        {
            this._kwnot_ = null;
            return;
        }

        if(this._kwnull_ == child)
        {
            this._kwnull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._kwas_ == oldChild)
        {
            setKwas((TKwas) newChild);
            return;
        }

        if(this._kwnot_ == oldChild)
        {
            setKwnot((TKwnot) newChild);
            return;
        }

        if(this._kwnull_ == oldChild)
        {
            setKwnull((TKwnull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
