/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AInitPropExternCall extends PExternCall
{
    private TClassid _classid_;

    public AInitPropExternCall()
    {
        // Constructor
    }

    public AInitPropExternCall(
        @SuppressWarnings("hiding") TClassid _classid_)
    {
        // Constructor
        setClassid(_classid_);

    }

    @Override
    public Object clone()
    {
        return new AInitPropExternCall(
            cloneNode(this._classid_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitPropExternCall(this);
    }

    public TClassid getClassid()
    {
        return this._classid_;
    }

    public void setClassid(TClassid node)
    {
        if(this._classid_ != null)
        {
            this._classid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classid_ == child)
        {
            this._classid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classid_ == oldChild)
        {
            setClassid((TClassid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
