/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIssetAttrExpr extends PExpr
{
    private TKwisset _kwisset_;
    private PExpr _expr_;
    private TAttrid _id_;

    public AIssetAttrExpr()
    {
        // Constructor
    }

    public AIssetAttrExpr(
        @SuppressWarnings("hiding") TKwisset _kwisset_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TAttrid _id_)
    {
        // Constructor
        setKwisset(_kwisset_);

        setExpr(_expr_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AIssetAttrExpr(
            cloneNode(this._kwisset_),
            cloneNode(this._expr_),
            cloneNode(this._id_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIssetAttrExpr(this);
    }

    public TKwisset getKwisset()
    {
        return this._kwisset_;
    }

    public void setKwisset(TKwisset node)
    {
        if(this._kwisset_ != null)
        {
            this._kwisset_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwisset_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TAttrid getId()
    {
        return this._id_;
    }

    public void setId(TAttrid node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwisset_)
            + toString(this._expr_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwisset_ == child)
        {
            this._kwisset_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwisset_ == oldChild)
        {
            setKwisset((TKwisset) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TAttrid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
