/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AReturnExpr extends PExpr
{
    private TKwreturn _kwreturn_;
    private PExpr _expr_;

    public AReturnExpr()
    {
        // Constructor
    }

    public AReturnExpr(
        @SuppressWarnings("hiding") TKwreturn _kwreturn_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setKwreturn(_kwreturn_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AReturnExpr(
            cloneNode(this._kwreturn_),
            cloneNode(this._expr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturnExpr(this);
    }

    public TKwreturn getKwreturn()
    {
        return this._kwreturn_;
    }

    public void setKwreturn(TKwreturn node)
    {
        if(this._kwreturn_ != null)
        {
            this._kwreturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwreturn_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwreturn_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwreturn_ == child)
        {
            this._kwreturn_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwreturn_ == oldChild)
        {
            setKwreturn((TKwreturn) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
