/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ASignature extends PSignature
{
    private final LinkedList<PParam> _params_ = new LinkedList<PParam>();
    private PType _type_;
    private final LinkedList<PClosureDecl> _closureDecls_ = new LinkedList<PClosureDecl>();

    public ASignature()
    {
        // Constructor
    }

    public ASignature(
        @SuppressWarnings("hiding") List<PParam> _params_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") List<PClosureDecl> _closureDecls_)
    {
        // Constructor
        setParams(_params_);

        setType(_type_);

        setClosureDecls(_closureDecls_);

    }

    @Override
    public Object clone()
    {
        return new ASignature(
            cloneList(this._params_),
            cloneNode(this._type_),
            cloneList(this._closureDecls_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignature(this);
    }

    public LinkedList<PParam> getParams()
    {
        return this._params_;
    }

    public void setParams(List<PParam> list)
    {
        this._params_.clear();
        this._params_.addAll(list);
        for(PParam e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public LinkedList<PClosureDecl> getClosureDecls()
    {
        return this._closureDecls_;
    }

    public void setClosureDecls(List<PClosureDecl> list)
    {
        this._closureDecls_.clear();
        this._closureDecls_.addAll(list);
        for(PClosureDecl e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._params_)
            + toString(this._type_)
            + toString(this._closureDecls_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._params_.remove(child))
        {
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._closureDecls_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PParam> i = this._params_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParam) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        for(ListIterator<PClosureDecl> i = this._closureDecls_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClosureDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
