/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStdImport extends PImport
{
    private PVisibility _visibility_;
    private TKwimport _kwimport_;
    private PModuleName _name_;

    public AStdImport()
    {
        // Constructor
    }

    public AStdImport(
        @SuppressWarnings("hiding") PVisibility _visibility_,
        @SuppressWarnings("hiding") TKwimport _kwimport_,
        @SuppressWarnings("hiding") PModuleName _name_)
    {
        // Constructor
        setVisibility(_visibility_);

        setKwimport(_kwimport_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new AStdImport(
            cloneNode(this._visibility_),
            cloneNode(this._kwimport_),
            cloneNode(this._name_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStdImport(this);
    }

    public PVisibility getVisibility()
    {
        return this._visibility_;
    }

    public void setVisibility(PVisibility node)
    {
        if(this._visibility_ != null)
        {
            this._visibility_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._visibility_ = node;
    }

    public TKwimport getKwimport()
    {
        return this._kwimport_;
    }

    public void setKwimport(TKwimport node)
    {
        if(this._kwimport_ != null)
        {
            this._kwimport_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwimport_ = node;
    }

    public PModuleName getName()
    {
        return this._name_;
    }

    public void setName(PModuleName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._visibility_)
            + toString(this._kwimport_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._visibility_ == child)
        {
            this._visibility_ = null;
            return;
        }

        if(this._kwimport_ == child)
        {
            this._kwimport_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._visibility_ == oldChild)
        {
            setVisibility((PVisibility) newChild);
            return;
        }

        if(this._kwimport_ == oldChild)
        {
            setKwimport((TKwimport) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((PModuleName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
