/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AVarReassignExpr extends PExpr
{
    private TId _id_;
    private PAssignOp _assignOp_;
    private PExpr _value_;

    public AVarReassignExpr()
    {
        // Constructor
    }

    public AVarReassignExpr(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAssignOp _assignOp_,
        @SuppressWarnings("hiding") PExpr _value_)
    {
        // Constructor
        setId(_id_);

        setAssignOp(_assignOp_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AVarReassignExpr(
            cloneNode(this._id_),
            cloneNode(this._assignOp_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarReassignExpr(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAssignOp getAssignOp()
    {
        return this._assignOp_;
    }

    public void setAssignOp(PAssignOp node)
    {
        if(this._assignOp_ != null)
        {
            this._assignOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignOp_ = node;
    }

    public PExpr getValue()
    {
        return this._value_;
    }

    public void setValue(PExpr node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._assignOp_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._assignOp_ == child)
        {
            this._assignOp_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._assignOp_ == oldChild)
        {
            setAssignOp((PAssignOp) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
