/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TDotdotdot extends Token
{
    public TDotdotdot()
    {
        super.setText("...");
    }

    public TDotdotdot(int line, int pos)
    {
        super.setText("...");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDotdotdot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDotdotdot(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDotdotdot text.");
    }
}
