/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwabort extends Token
{
    public TKwabort()
    {
        super.setText("abort");
    }

    public TKwabort(int line, int pos)
    {
        super.setText("abort");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwabort(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwabort(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwabort text.");
    }
}
