/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwassert extends Token
{
    public TKwassert()
    {
        super.setText("assert");
    }

    public TKwassert(int line, int pos)
    {
        super.setText("assert");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwassert(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwassert(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwassert text.");
    }
}
