/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwdo extends Token
{
    public TKwdo()
    {
        super.setText("do");
    }

    public TKwdo(int line, int pos)
    {
        super.setText("do");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwdo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwdo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwdo text.");
    }
}
