/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwextern extends Token
{
    public TKwextern()
    {
        super.setText("extern");
    }

    public TKwextern(int line, int pos)
    {
        super.setText("extern");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwextern(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwextern(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwextern text.");
    }
}
