/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwfor extends Token
{
    public TKwfor()
    {
        super.setText("for");
    }

    public TKwfor(int line, int pos)
    {
        super.setText("for");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwfor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwfor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwfor text.");
    }
}
