/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwisset extends Token
{
    public TKwisset()
    {
        super.setText("isset");
    }

    public TKwisset(int line, int pos)
    {
        super.setText("isset");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwisset(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwisset(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwisset text.");
    }
}
