/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwimport extends Token
{
    public TKwimport()
    {
        super.setText("import");
    }

    public TKwimport(int line, int pos)
    {
        super.setText("import");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwimport(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwimport(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwimport text.");
    }
}
