/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwmeth extends Token
{
    public TKwmeth()
    {
        super.setText("fun");
    }

    public TKwmeth(int line, int pos)
    {
        super.setText("fun");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwmeth(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwmeth(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwmeth text.");
    }
}
