/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwnew extends Token
{
    public TKwnew()
    {
        super.setText("new");
    }

    public TKwnew(int line, int pos)
    {
        super.setText("new");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwnew(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwnew(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwnew text.");
    }
}
