/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKwself extends Token
{
    public TKwself()
    {
        super.setText("self");
    }

    public TKwself(int line, int pos)
    {
        super.setText("self");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwself(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwself(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwself text.");
    }
}
