/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TQuad extends Token
{
    public TQuad()
    {
        super.setText("::");
    }

    public TQuad(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQuad(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQuad(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQuad text.");
    }
}
